name: Python package

on: [push,workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # - name: Test with pytest
      #   run: pip test
      - name: Run python file
        id: web_health_check
        run: |
          result=$(url=google.com python url-check.py)
          echo $result
      #     url=google.com python url-check.py
      - name: Check result
        continue-on-error: true
        if: ${{ env.result }} == '200'
        run: echo Đây là website
      - name: Check result 1
        # continue-on-error: true
        if: ${{ env.result }} != '200'
        run: echo Đây là website
      # - name: Check web health check
      #   continue-on-error: true
      #   env:
      #     code: ${{ steps.web_health_check.output }}
      #   if: $code == '200'
      #   run: echo steps.web_health_check.output
      # - name: Check web health check 1
      #   continue-on-error: true
      #   if: ${{ steps.web_health_check.output }} != '200'
      #   run: echo Đây là website

