name: Copy file

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: requirements.txt
      - name: Read file
        run: |
          ls
          #cat requirements.txt
      - name: Read package.json
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./requirements.txt
      - name: Echo package.json
        run: echo "${{ steps.package.outputs.content }}"
#       - name: Set up Python ${{ matrix.python-version }}
#         uses: actions/setup-python@v4
#         with:
#           python-version: "3.10"
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt
#       # - name: Test with pytest
#       #   run: pip test
#       - name: Run python file
#         id: web_health_check
#         run: |
#           echo "result=$(url=google1.com python url-check.py)" >> $GITHUB_OUTPUT
#       #     url=google.com python url-check.py
#       - name: Check result
#         continue-on-error: true
#         if: ${{ steps.web_health_check.outputs.result == '200' }}
#         run: echo ${{ steps.web_health_check.outputs.result }}
#       - name: Check result 1
#         # continue-on-error: true
#         if: ${{ steps.web_health_check.outputs.result != '200' }}
#         run: echo ${{ steps.web_health_check.outputs.result }}
